service: designo-serverless

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "dynamodb:PutItem"
            - "dynamodb:GetItem"
            - "dynamodb:DeleteItem"
            - "dynamodb:Scan"
            - "lambda:InvokeFunction"
            - "lambda:InvokeFunctionUrl"
            - "secretsmanager:GetSecretValue"
            - "s3:GetObject"
          Resource:
            - "arn:aws:s3:::designo-image-bucket/*"
package:
  patterns:
    - "!coverage/**"
    - "!.github/**"
    - "!.nvmrc"
    - "!.tmp/**"
    - "!tests/**"

functions: ${file(yml/functions.yml)}

plugins:
  - serverless-webpack
  - serverless-appsync-plugin

custom:
  webpack:
    webpackConfig: webpack.config.js
    excludeFiles: tests/**
    keepOutputDirectory: false
    serializedCompile: true
    packager: yarn

appSync:
  name: designo-graphql
  authentication:
    type: API_KEY
  apiKeys:
    - name: jason3
      description: Jason's API key.
      expiresAfter: 1M
  schema:
    - "src/graphql/*.graphql"
  pipelineFunctions: ${file(yml/appsync/pipelineFunctions.yml)}
  resolvers: ${file(yml/appsync/resolvers.yml)}
  dataSources: ${file(yml/appsync/dataSources.yml)}

resources:
  - ${file(yml/resources/cloudfront.yml)}
  - ${file(yml/resources/dynamo.yml)}
  - ${file(yml/resources/mappings.yml)}
  - ${file(yml/resources/parameters.yml)}
  - ${file(yml/resources/s3.yml)}
