name: Spec Tests and deployment

on:
  push:
    branches:
      - main

jobs:
  productionDeployment:
    name: productionDeployment
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://test.com
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn
        run: yarn
      - name: productionDeployment
        run: yarn test:ci
      - name: Install Plugin and Deploy
        uses: serverless/github-action@v3.2
        with:
          args: -c "serverless plugin install --name serverless-plugin-typescript serverless-appsync-plugin && serverless deploy"
          entrypoint: /bin/sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
